USE [master]
GO
/****** Object:  Database [Shop]    Script Date: 10/12/2023 19:36:28 ******/
CREATE DATABASE [Shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Shop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Shop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Shop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Shop] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Shop] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Shop] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Shop] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Shop] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Shop] SET ARITHABORT OFF 
GO
ALTER DATABASE [Shop] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Shop] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Shop] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Shop] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Shop] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Shop] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Shop] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Shop] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Shop] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Shop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Shop] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Shop] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Shop] SET RECOVERY FULL 
GO
ALTER DATABASE [Shop] SET  MULTI_USER 
GO
ALTER DATABASE [Shop] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Shop] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Shop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Shop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Shop] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Shop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Shop', N'ON'
GO
ALTER DATABASE [Shop] SET QUERY_STORE = ON
GO
ALTER DATABASE [Shop] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Shop]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[CUSTID] [int] IDENTITY(1,1) NOT NULL,
	[NAMA] [varchar](200) NULL,
	[ISVALID] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StatusStock]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StatusStock](
	[StatusID] [int] NOT NULL,
	[STATUS] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Stock]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stock](
	[StockID] [int] IDENTITY(1,1) NOT NULL,
	[Quantity] [int] NULL,
	[Price] [float] NULL,
	[Status] [int] NULL,
	[CreatedOn] [datetime] NULL,
	[UpdatedOn] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StockDetail]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StockDetail](
	[SDID] [int] IDENTITY(1,1) NOT NULL,
	[IDSTOCK] [int] NULL,
	[STOCKNAME] [varchar](500) NULL,
	[LICENSEYEAR] [varchar](10) NULL,
	[DISTRIBUTOR] [varchar](1000) NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[COLOR] [varchar](20) NULL,
	[CREATEDON] [datetime] NULL,
	[UPDATEDON] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRANSACTION]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRANSACTION](
	[TID] [int] IDENTITY(1,1) NOT NULL,
	[IDCUST] [int] NULL,
	[CREATEDON] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TransactionDetail]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TransactionDetail](
	[DETAILID] [int] IDENTITY(1,1) NOT NULL,
	[IDT] [int] NULL,
	[IDSTOCK] [int] NULL,
	[QUANTITY] [int] NULL,
	[PRICE] [float] NULL,
	[CREATEDON] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[Stock_DELETESTOCK]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

 CREATE PROCEDURE [dbo].[Stock_DELETESTOCK]
@ID VARCHAR(200)
	-- Add the parameters for the stored procedure here
AS
BEGIN
	UPDATE Stock
	SET STATUS=2
	WHERE StockID=@ID

END
GO
/****** Object:  StoredProcedure [dbo].[Stock_GetStockByID]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Stock_GetStockByID]
@ID VARCHAR(200)
	-- Add the parameters for the stored procedure here
AS
BEGIN
	SELECT 
		StockID,
		STOCKNAME NAMASTOCK,
		LICENSEYEAR TAHUNLISENSI,
		DISTRIBUTOR,
		DESCRIPTION DESKRIPSI,
		COLOR WARNA,
		Quantity KUANTITAS,
		PRICE HARGA,
		A.CreatedOn TANGGALMASUK
	FROM Stock A
	LEFT JOIN StockDetail B ON A.StockID=B.IDSTOCK
	LEFT JOIN StatusStock C ON A.Status=C.StatusID
	WHERE StockID=@ID

END
GO
/****** Object:  StoredProcedure [dbo].[Stock_GetStockList]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Stock_GetStockList] 
	-- Add the parameters for the stored procedure here
AS
BEGIN
	SELECT 
		A.StockID,
		STOCKNAME NAMASTOCK,
		LICENSEYEAR TAHUNLISENSI,
		DISTRIBUTOR,
		DESCRIPTION DESKRIPSI,
		COLOR WARNA,
		Quantity KUANTITAS,
		PRICE HARGA,
		A.CreatedOn TANGGALMASUK
	FROM Stock A
	LEFT JOIN StockDetail B ON A.StockID=B.IDSTOCK
	LEFT JOIN StatusStock C ON A.Status=C.StatusID
	WHERE A.STATUS<>2

END
GO
/****** Object:  StoredProcedure [dbo].[Stock_InsertStock]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Stock_InsertStock]
	@Quantity varchar(200),
	@PRICE FLOAT,
	@CREATEDON VARCHAR(50),
	@STOCKNAME VARCHAR(200),
	@LICENSEYEAR VARCHAR(50),
	@DISTRIBUTOR VARCHAR(200),
	@DESCRIPTION VARCHAR(MAX),
	@COLOR VARCHAR(50)
AS
BEGIN
	DECLARE @IDSTOCK TABLE (IDSTOCK	 INT)
	INSERT INTO Stock
	output inserted.StockID INTO @IDSTOCK
	VALUES(@Quantity,@PRICE,1,@CREATEDON,@CREATEDON)

	INSERT INTO StockDetail
	SELECT IDSTOCK,
			@STOCKNAME,
			@LICENSEYEAR,
			@DISTRIBUTOR,
			@DESCRIPTION,
			@COLOR,
			@CREATEDON,
			@CREATEDON
	FROM @IDSTOCK

	SELECT IDSTOCK FROM @IDSTOCK
END
GO
/****** Object:  StoredProcedure [dbo].[Stock_UPDATEStock]    Script Date: 10/12/2023 19:36:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Stock_UPDATEStock]
	@ID VARCHAR(50),
	@Quantity varchar(200),
	@PRICE FLOAT,
	@CREATEDON VARCHAR(50),
	@STOCKNAME VARCHAR(200),
	@LICENSEYEAR VARCHAR(50),
	@DISTRIBUTOR VARCHAR(200),
	@DESCRIPTION VARCHAR(MAX),
	@COLOR VARCHAR(50)
AS
BEGIN

	UPDATE  Stock
	SET Quantity=@Quantity,
		PRICE=@PRICE,
		UpdatedOn=@CREATEDON
	WHERE STOCKID=@ID

	UPDATE StockDetail
	SET STOCKNAME=@STOCKNAME,
		LICENSEYEAR=@LICENSEYEAR,
		DISTRIBUTOR=@DISTRIBUTOR,
		DESCRIPTION=@DESCRIPTION,
		COLOR=@COLOR,
		UPDATEDON=@CREATEDON
	WHERE IDSTOCK=@ID

END
GO
USE [master]
GO
ALTER DATABASE [Shop] SET  READ_WRITE 
GO
